apiVersion: v1
kind: Service
metadata:
  name: webrtc-media-service
spec:
  selector:
    app: webrtc-media-app
  ports:
    - protocol: TCP
      port: 80 # The port that the service will be exposed on
      targetPort: 3000 # The port that the container is listening on
    - protocol: UDP
      port: 3478 # STUN/TURN port for WebRTC
      targetPort: 3478
    - protocol: UDP
      port: 40000-40500 # RTP ports for WebRTC media
      targetPort: 40000-40500
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-media-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webrtc-media-app
  template:
    metadata:
      labels:
        app: webrtc-media-app
    spec:
      containers:
        - name: webrtc-media-container
          image: your-docker-image:latest
          ports:
            - containerPort: 3000
            - containerPort: 3478
            - containerPort: 40000-40500
          env:
            - name: ENV_VARIABLE_NAME
              value: 'your-env-variable-value'
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '500m'
              memory: '256Mi'
