export enum RTC_EVENTS {
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  CREATE_TRANSPORT = 'CREATE_TRANSPORT',
  CONNECT_TRANSPORT = 'CONNECT_TRANSPORT',
  PRODUCE = 'PRODUCE',
  CONSUME = 'CONSUME',
  PRODUCER_DATA = 'PRODUCER_DATA',
  CREATE_DATA_CONSUMER = 'CREATE_DATA_CONSUMER',
  SEND_DATA = 'SEND_DATA',
  GET_EXISTING_ROOM_PRODUCERS = 'GET_EXISTING_ROOM_PRODUCERS',
  NEW_PRODUCER = 'NEW_PRODUCER',
  RESUME_CONSUMER = "RESUME_CONSUMER",
}
export const EVENT_NAME = 'rtc-event';
